Update terraform-deploy.yml

diff --git a/.github/workflows/terraform-deploy.yml b/.github/workflows/terraform-deploy.yml
--- a/.github/workflows/terraform-deploy.yml
+++ b/.github/workflows/terraform-deploy.yml
@@ -40,15 +40,19 @@ jobs:
       uses: actions/checkout@v4
 
     - name: list directory
-      run : ls -la
+      run : |
+            ls -la
+            cd terraform
+            terraform init
+            terraform plan
 
-    - name: Check Terraform Files
-      working-directory: terraform
-      run: |
-        if [ ! -d "./terraform" ] || [ -z "$(ls -A ./terraform/*.tf)" ]; then
-          echo "Error: No Terraform files found in ./terraform directory"
-          exit 1
-        fi
+    # - name: Check Terraform Files
+    #   working-directory: terraform
+    #   run: |
+    #     if [ ! -d "terraform" ] || [ -z "$(ls -A terraform/*.tf)" ]; then
+    #       echo "Error: No Terraform files found in ./terraform directory"
+    #       exit 1
+    #     fi
 
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
